name: dars_bin
description: A simple university selection screen.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  # For SVG support (optional if you use SVG icons)
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/22.png # Put your book + magnifier icon here

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf
          weight: 700
